from enum import Enum

class CircuitReason(str,Enum):
    STATE_UNKNOWN="STATE_UNKNOWN"; STATE_CONFLICT="STATE_CONFLICT"; WEBSOCKET_STALE="WS_STALE"
    EXCHANGE_UNAVAILABLE="EXCHANGE_UNAVAILABLE"; CLOCK_INVALID="CLOCK_INVALID"; RATE_LIMITED="RATE_LIMITED"
    DATABASE_FAILURE="DATABASE_FAILURE"; DISK_LOW="DISK_LOW"; MEMORY_CRITICAL="MEMORY_CRITICAL"
    CPU_SATURATION="CPU_SATURATION"; NETWORK_DEGRADED="NETWORK_DEGRADED"; WS_FAILURE="WS_FAILURE"
    AUTH="AUTH"; PROTECTION_UNKNOWN="PROTECTION_UNKNOWN"; ORDER_RESULT_UNKNOWN="ORDER_RESULT_UNKNOWN"
    CONFIGURATION_MISMATCH="CONFIGURATION_MISMATCH"; RATE_LIMIT="RATE_LIMITED"

def should_freeze(reason):
    try:
        CircuitReason(reason)
        return True
    except ValueError:
        return True
